### ISSUE TITLE
로그인 로직 구현

### ISSUE THREAD

**Issue by joan-KIM** [joan-KIM/soboro#37]
## 개요
로그인 처리 로직 구현

## 완료 조건
- [x] 로그인 실패시 알림(임의로 처리)
- [x] 로그인 성공시 타임라인 페이지로 이동

**Comment by ParkEunwoo** [comment]
- 로그인 성공시 타임라인 페이지로 이동
- 회원가입 성공시 프로필 추가 페이지로 이동
이거로 바뀐거 아니었나

**Comment by joan-KIM** [comment]
오 맞아
