### ISSUE TITLE
내비게이션 바

### ISSUE THREAD

**Issue by joan-KIM** [joan-KIM/soboro#64]
## 완료 조건
- [x] 내비게이션 바 마크업, 디자인 적용
- [x] 내비게이션 바 하단에 위치 고정
- [x] 페이지 라우팅
- [x] 내비게이션 필요한 페이지에 추가
- [x] 현재 페이지 하이라이트 표시

**Comment by ParkEunwoo** [comment]
현재 페이지 하이라이트 표시

**Comment by ParkEunwoo** [comment]
네비게이션 컴포넌트는 각 페이지마다 복붙으로 들어간다기 보다는 react-router로 적절히 처리 가능하지 않을지.. 아마 outlet?
